"use client";

import { FormEvent, useEffect, useState } from "react";
import { DashboardShell } from "../../../components/dashboard-shell";
import { apiRequest, uploadApiRequest } from "../../../lib/api";
import { canConfirmTimetableImport } from "../../../lib/timetable-import";

type Match = { sourceName: string; status: "matched" | "new" | "ambiguous"; workload?: number; candidates?: Array<{ id: string; name: string }> };
type Preview = { totals: Record<string, number>; detected: { teachers: string[]; subjects: string[]; classes: string[]; periods: number[]; days: string[]; workloads: Record<string, number> }; teacherMatches: Match[]; duplicateRows: number[]; invalidRows: Array<{ rowNumber: number; message: string }>; warnings: string[]; blockingErrors: string[]; affectedFixtureCount: number };
type PreviewResponse = { batchId: string; preview: Preview };
type History = { id: string; status: string; originalFileName: string; fileType: string; importedRows: number; warningCount: number; errorCount: number; createdAt: string };

export default function TimetableImportPage() {
  const [file, setFile] = useState<File>(); const [progress, setProgress] = useState(0); const [processing, setProcessing] = useState(false); const [result, setResult] = useState<PreviewResponse>(); const [error, setError] = useState(""); const [importing, setImporting] = useState(false); const [summary, setSummary] = useState<Record<string, number>>(); const [history, setHistory] = useState<History[]>([]); const [mappings, setMappings] = useState<Record<string, string>>({}); const [confirmTeacherUpdates, setConfirmTeacherUpdates] = useState(false);
  const loadHistory = async () => { try { const data = await apiRequest<{ batches: History[] }>("/timetable-imports"); setHistory(data.batches); } catch { /* preview remains usable */ } };
  useEffect(() => { void loadHistory(); }, []);
  const preview = async (event: FormEvent) => { event.preventDefault(); if (!file) return; setError(""); setSummary(undefined); setProcessing(true); setProgress(0); try { const form = new FormData(); form.append("file", file); setResult(await uploadApiRequest<PreviewResponse>("/timetable-imports/preview", form, setProgress)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to process timetable"); } finally { setProcessing(false); } };
  const confirm = async () => { if (!result || !window.confirm("Replace the current timetable with this validated preview? Historical fixtures will be preserved.")) return; setImporting(true); setError(""); try { const data = await apiRequest<{ summary: Record<string, number> }>(`/timetable-imports/${result.batchId}/confirm`, { method: "POST", body: JSON.stringify({ confirmReplace: true, confirmTeacherUpdates, teacherMappings: mappings }) }); setSummary(data.summary); await loadHistory(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Import failed"); } finally { setImporting(false); } };
  return <DashboardShell><div className="mb-5"><h2 className="text-2xl font-bold text-ink">Timetable Import</h2><p className="mt-1 text-sm text-slate-600">Upload a PDF or CSV. Parsing and all school-scoped changes happen securely on the server.</p></div>
    <form className="rounded-2xl border border-slate-200 bg-white p-5" onSubmit={preview}><label className="block text-sm font-semibold">Timetable file (PDF or CSV, max 5 MB)<input accept=".pdf,.csv,application/pdf,text/csv" className="mt-2 block w-full rounded-xl border border-slate-300 p-3" onChange={(event) => { setFile(event.target.files?.[0]); setResult(undefined); setSummary(undefined); }} required type="file"/></label>{processing ? <div className="mt-4"><div className="h-2 overflow-hidden rounded bg-slate-100"><div className="h-full bg-primary transition-all" style={{ width: `${progress}%` }}/></div><p className="mt-2 text-sm">{progress < 100 ? `Uploading ${progress}%` : "Processing and validating on server…"}</p></div> : null}<button className="mt-4 rounded-xl bg-primary px-4 py-3 font-semibold text-white disabled:opacity-60" disabled={!file || processing}>{processing ? "Processing…" : result ? "Retry preview" : "Upload and preview"}</button></form>
    {error ? <p className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700" role="alert">{error}</p> : null}
    {result ? <section className="mt-5 space-y-5"><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{Object.entries(result.preview.totals).map(([label, value]) => <div className="rounded-xl border bg-white p-4" key={label}><p className="text-xs text-slate-500">{label.replace(/([A-Z])/g, " $1")}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>)}</div>
      {result.preview.blockingErrors.length ? <div className="rounded-xl border border-red-200 bg-red-50 p-4"><h3 className="font-bold text-red-800">Blocking errors</h3>{result.preview.blockingErrors.map((item) => <p className="mt-1 text-sm text-red-700" key={item}>{item}</p>)}</div> : null}
      {result.preview.warnings.length ? <div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><h3 className="font-bold text-amber-900">Warnings</h3>{result.preview.warnings.map((item) => <p className="mt-1 text-sm" key={item}>{item}</p>)}</div> : null}
      <div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Teacher detected</th><th className="p-3">Match</th><th className="p-3">Workload</th><th className="p-3">Resolution</th></tr></thead><tbody>{result.preview.teacherMatches.map((match) => <tr className="border-t" key={match.sourceName}><td className="p-3 font-semibold">{match.sourceName}</td><td className="p-3">{match.status}</td><td className="p-3">{match.workload ?? "Not supplied"}</td><td className="p-3">{match.status === "ambiguous" ? <select className="rounded-lg border p-2" onChange={(event) => setMappings((value) => ({ ...value, [match.sourceName]: event.target.value }))} value={mappings[match.sourceName] ?? ""}><option value="">Choose teacher</option>{match.candidates?.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</select> : match.status === "new" ? "Create new teacher" : "Use existing teacher"}</td></tr>)}</tbody></table></div>
      <label className="flex items-start gap-3 rounded-xl border bg-white p-4 text-sm"><input checked={confirmTeacherUpdates} className="mt-1" onChange={(event) => setConfirmTeacherUpdates(event.target.checked)} type="checkbox"/><span>Confirm timetable-driven workload changes for existing teachers. Names and phone numbers are not overwritten.</span></label>
      <button className="rounded-xl bg-primary px-5 py-3 font-semibold text-white disabled:opacity-50" disabled={importing || !canConfirmTimetableImport(result.preview, mappings)} onClick={() => void confirm()} type="button">{importing ? "Importing…" : "Confirm and replace timetable"}</button>
    </section> : null}
    {summary ? <section className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><h3 className="font-bold text-emerald-900">Import completed</h3><div className="mt-3 grid gap-2 sm:grid-cols-3">{Object.entries(summary).map(([key, value]) => <p className="text-sm" key={key}><span className="font-semibold">{key}:</span> {value}</p>)}</div></section> : null}
    <section className="mt-7"><h3 className="font-bold">Recent import history</h3><div className="mt-3 overflow-x-auto rounded-xl border bg-white"><table className="min-w-full text-left text-sm"><thead><tr><th className="p-3">File</th><th className="p-3">Status</th><th className="p-3">Rows</th><th className="p-3">Date</th></tr></thead><tbody>{history.map((item) => <tr className="border-t" key={item.id}><td className="p-3">{item.originalFileName} ({item.fileType})</td><td className="p-3">{item.status}</td><td className="p-3">{item.importedRows}</td><td className="p-3">{new Date(item.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div></section>
  </DashboardShell>;
}
